import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Dating App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h4>You need to be logged in to see the content</h4>
        <Link href="/auth/login">
          <a>Log in</a>
        </Link>{" "}
        or{" "}
        <Link href="/auth/signup">
          <a>Sign up</a>
        </Link>
      </main>
    </Layout>
  );
}
